In [1]:
import pandas as pd 
import numpy as np

In [2]:
df = pd.read_csv("vokabeln.csv")
df

        Latein                                         Deutsch  Kartei Wortart
0     quis es?                     Wer bist Du?; Wie heißt Du?      12       x
1      Ego sum                              Ich bin; ich heiße      12       x
2      familia                                     die Familie      12       s
3       servus                          der Diener; der Sklave      12       s
4        serva                       die Dienerin; die Sklavin      12       s
..         ...                                             ...     ...     ...
499        dum  (solange) bis; solange; (m. Ind. Präs) während       8       x
500   postquam                                         nachdem      10       x
501   quamquam                                          obwohl      10       x
502      murus                                       die Mauer      10       s
503  lupa; -ae                                      die Wölfin      11       s

[504 rows x 4 columns]

In [3]:
df["Kartei"] = 1
df
df.to_csv("vokabeln_mob.csv", index=False)

In [5]:
df

        Latein                                         Deutsch  Kartei Wortart
0     quis es?                     Wer bist Du?; Wie heißt Du?       1       x
1      Ego sum                              Ich bin; ich heiße       1       x
2      familia                                     die Familie       1       s
3       servus                          der Diener; der Sklave       1       s
4        serva                       die Dienerin; die Sklavin       1       s
..         ...                                             ...     ...     ...
499        dum  (solange) bis; solange; (m. Ind. Präs) während       1       x
500   postquam                                         nachdem       1       x
501   quamquam                                          obwohl       1       x
502      murus                                       die Mauer       1       s
503  lupa; -ae                                      die Wölfin       1       s

[504 rows x 4 columns]

# nach XLS und zurück

In [8]:
df.to_excel("vokabeln.xlsx", index=True)

In [9]:
# INDEX in XLS löschen
df2 = pd.read_excel("vokabeln.xlsx")

In [10]:
df2.head()

     Latein                      Deutsch  Kartei Wortart
0  quis es?  Wer bist Du?; Wie heißt Du?       1       x
1   Ego sum           Ich bin; ich heiße       1       x
2   familia                  die Familie       1       s
3    servus       der Diener; der Sklave       1       s
4     serva    die Dienerin; die Sklavin       1       s

In [11]:
df2.to_csv("vokabeln.csv", index=False)

In [15]:
zeile = df.shape[0]
temp = pd.DataFrame(index=[zeile], columns=["Latein", "Deutsch", "Kartei"])
temp.iloc[0,0] = "L"
temp.iloc[0,1] = "D"
temp.iloc[0,2] = 1
df= df.append(temp)

In [7]:
df.loc[df["Latein] == "huc"]

SyntaxError: invalid syntax (4060792761.py, line 1)

In [18]:
def add(df):
    # Startwerte
    done = False
    zeile = df.shape[0]
    print("\nHier gibst Du neue Vokabeln ein!")
    print(f"Das zuletzt eingetragene Wort ist {df.iloc[zeile-1, 1]}.")
    while not done:
        #Eingabe
        la = input("\nLatein Wort: ")
        de = input("Deutsches Wort (Trennen mit ;): ")
        #Speichern
        temp = pd.DataFrame(index=[zeile], columns=["Latein", "Deutsch", "Kartei"])
        temp.iloc[0,0] = la
        temp.iloc[0,1] = de
        temp.iloc[0,2] = 1
        df = df.append(temp)

        # Loop
        weiter = input("Noch ein Wort (n = nein)? ")
        if weiter == "n":
            done = True
        else:
            zeile +=1
    return df

In [19]:
add(df)

Hier gibst Du neue Vokabeln ein!
Das zuletzt eingetragene Wort ist D.

Latein Wort: bli
Deutsches Wort (Trennen mit ;): bla ; blub
Noch ein Wort (n = nein)?

Latein Wort: hubsus
Deutsches Wort (Trennen mit ;): hubsi; pfopf
Noch ein Wort (n = nein)? n

      Latein                             Deutsch Kartei
0   quis es?         Wer bist Du?; Wie heißt Du?      1
1    Ego sum                  Ich bin; ich heiße      1
2    familia                         die Famiele      1
3     servus              der Diener; der Sklave      1
4      serva          die dienserin; die Sklavin      1
5    dominus              der Herr; der Hausherr      1
6     domina          die Herrin; die Hausherrin      1
7   negotium  das Geschäft (machen); die Aufgabe      1
8          L                                   D      1
9        bli                          bla ; blub      1
10    hubsus                        hubsi; pfopf      1

In [25]:
def training(df, n = 3):
    df.sort_values(['Kartei'], ascending=[1], inplace=True)
    modus = input("Willst Du die Worte in Latein (l) oder Deutsch (d) sehen?")
    if modus == "l":
        for i in range(n):
            antwort = input(f"\nÜberlege das deutsche Wort für:  {df.iloc[i,0]} ! Weiter? ")
            richtig = input("war es richtig (j)?")
            if richtig == "j":
                df.iloc[i,2] += 1
    if modus == "d":
        for i in range(n):
            antwort = input(f"\nÜberlege das lateinische Wort für:  {df.iloc[i,1]} ! Weiter? ")
            richtig = input("war es richtig (j)?")
            if richtig == "j":
                df.iloc[i,2] += 1
    df.sort_index(inplace=True)
    return df

In [26]:
training(df)

Willst Du die Worte in Latein (l) oder Deutsch (d) sehen?l

Überlege das deutsche Wort für:  quis es? ! Weiter?
war es richtig (j)?j

Überlege das deutsche Wort für:  Ego sum ! Weiter?
war es richtig (j)?k

Überlege das deutsche Wort für:  familia ! Weiter?
war es richtig (j)?j

     Latein                             Deutsch Kartei
0  quis es?         Wer bist Du?; Wie heißt Du?      2
1   Ego sum                  Ich bin; ich heiße      1
2   familia                         die Famiele      2
3    servus              der Diener; der Sklave      1
4     serva          die dienserin; die Sklavin      1
5   dominus              der Herr; der Hausherr      1
6    domina          die Herrin; die Hausherrin      1
7  negotium  das Geschäft (machen); die Aufgabe      1
8         L                                   D      1

In [27]:
#änderung nach position
df.iloc[5,1] = "l'età"
df

,de,it,bsp,lektion,wortschatz,kartei,check
0,"Größe, Höhe",l'altezza,"La bambina ha un'altezza di 1,30 metri",1.01,1,2,2021-03-28 13:38:02.743579
1,"bürgerlich, zivil",civile,I soldati possono indossare abiti civile quand...,1.01,1,2,2021-03-28 13:38:22.162993
2,Familienname,il cognome,"In Italia, normalmente, i bambini ricevono il ...",1.01,1,2,2021-03-28 13:38:27.806482
3,Herr,il don,In alcune zone del Sud si dice ancora Don o Do...,1.01,1,2,2021-03-28 13:38:39.482173
4,Frau,la donna,Franco ha un appuntamento con una donna e va a...,1.01,1,2,2021-03-28 13:38:43.693998
5,Alter,l'età,"Raggiunta una certa età, una persona deve esse...",1.01,1,1,2021-03-28 13:38:54.082224
6,Identität,l'identità,Il carattere fa parte dell'identità di una per...,1.01,1,1,2021-03-28 12:43:17.814468
7,Adresse,l'indirizzo,"Via Milano 7, è questo il Suo indirizzo corretto?",1.01,1,1,2021-03-28 12:43:17.814468
8,Individuum,l'individuo,La legge prevende ditrattare ogni individuo al...,1.01,1,1,2021-03-28 12:43:17.814468
9,er,lui,Lui è un don.,1.01,1,1,2021-03-28 12:43:17.814468
10,sie,lei,Lei è una donna.,1.01,1,1,2021-03-28 12:43:17.814468
11,Ehemann,il marito,Vivo con mio marito in un paese vicino a Roma,1.01,1,1,2021-03-28 12:43:17.814468
12,Ehefrau,la moglie,La moglie del signor Martini fa la casalinga.,1.01,1,1,2021-03-28 12:47:56.809741
13,Name,il nome,"Mi dica il suo nome completo, per favore!",1.01,1,1,2021-03-28 13:01:36.951276

In [30]:
df.to_csv("vokabeln.csv", index=False)

# Spielerei

In [5]:
np.unique(df["kartei"].values, return_counts = True)

(array([2, 3]), array([10,  5]))